DROP TABLE CALBOARD;
DROP SEQUENCE CALBOARD_SEQ;

CREATE SEQUENCE CALBOARD_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE CALBOARD(
	SEQ NUMBER PRIMARY KEY,
	ID VARCHAR2(50) NOT NULL,
	TITLE VARCHAR2(1000) NOT NULL,
	CONTENT VARCHAR2(2000) NOT NULL,
	MDATE VARCHAR2(12) NOT NULL, -- 일정을 끊어가지고 오는 애
	REGDATE DATE NOT NULL
);

SELECT * FROM CALBOARD;

-- 년월일의 게시판 글 (getCalList) 파라미터 Map result:Dto 
SELECT SEQ, ID, TITLE, CONTENT, MDATE, REGDATE
FROM CALBOARD
WHERE ID='' AND SUBSTR(MDATE,1,8)='YYYYMMDD';

-- 새글 일정 입력 (insertCalBoard) param: Dto
INSERT INTO CALBOARD
(SEQ, ID, TITLE, CONTENT, MDATE, REGDATE)
VALUES(CALBOARD_SEQ.NEXTVAL, 'M001', '제목', '내용', '201903191409', SYSDATE);

-- 년월일의 글 개수 (getCalView) Map Integer
SELECT COUNT(*) 
FROM CALBOARD
WHERE ID='M001' AND SUBSTR(MDATE,1,8)='20190319';

-- 달력 년월의 해당 일수에 따른 글 (3개씩으로 제한) (getCalViewList) Map Dto
SELECT SEQ, ID, TITLE, CONTENT, MDATE, REGDATE
	FROM(SELECT ROW_NUMBER() OVER(PARTITION BY SUBSTR(MDATE,1,8) ORDER BY MDATE) RN,
			SEQ, ID, TITLE, CONTENT, MDATE, REGDATE 
			FROM CALBOARD
			WHERE ID='M001' AND SUBSTR(MDATE,1,6) = '201903')
	WHERE RN BETWEEN 1 AND 3;









